Select
total_sent_through_medium,
total_sent_through_medium__st,
created_date,
total_spend,
currency,
voucher_worth,
medium,
month_paid,
cost_per_medium_used_once,
cost_per_medium_used_once__st,
_sdc_table_version,
year_month,
__sdc_sheet_id,
__sdc_row,
_sdc_received_at,
_sdc_sequence,
year,
country__ksa_egypt_ as Country_KSA_Egypt,
spend_per_day,
month,
_sdc_batched_at,
_sdc_extracted_at,
need_to_be_filled,
code,
updated_date,
__sdc_spreadsheet_id
from `noted-computing-279322.lazurde_influencers_affiliates.Influencer_Codes`
where lower(country__ksa_egypt_) = 'egypt'
or lower(country__ksa_egypt_) = 'both'